### PR TITLE
Optimization

### PR DESCRIPTION
**Pull request by StructuredObjects**
Type hinting added, removed useless if && replaced useless code

### CODE REVIEW

**Comment by 6nz** [comment]
LOL

**Comment by 6nz** [comment]
this shit is literally pointless

**Comment by 6nz** [comment]
image
what was the point of that?

**Comment by 6nz** [comment]
Replacing the os._exit(1) to exit() is just stupid
image

**Comment by 6nz** [comment]
exit() and sys.exit cannot stop threads. if someone' program is threaded it wont fully exit

**Comment by 6nz** [comment]
adding hinting is also pointless

**Comment by 6nz** [comment]
if it was that important then I would have added it a long time ago

**Comment by 6nz** [comment]
oh and btw you broke the script

**Comment by 6nz** [comment]
all the outgoing requests are using 1 session which u removed for no reason
image

**Comment by 6nz** [comment]
here:
image

**Comment by 6nz** [comment]
And you are the guy who asks 20$/h for coding help lmao, you dont even know anything

**Review by 6nz — COMMENTED** [review]
### Pointless
**???**
image

**Replacing the os._exit(1) to exit() is not a good idea**
> os._exit(1) will stop the program even if it's threaded, sys.exit and exit() will not close the app
image

**Hinting**

> As I said hinting is pointless wont speed up or slow down the code, nothing gonna change

**Deleting the session**

> ?? Whats the point of that, that breaks the whole script lmao

image
image
**all the requests are using that one session**

### Deny, I expected something better than this from a guy who asks 20$/h for coding
**also this doesnt require any skill I can tell you just used vsc or pycharm to auto add the hints and stuff**

**Comment by 6nz** [comment]
❌

**Comment by StructuredObjects** [comment]
Your starting a new session every time u run use that function. wow this is getting screenshot

**Comment by 6nz** [comment]
Where

**Comment by 6nz** [comment]
image

**Comment by 6nz** [comment]
Where is the function

**Comment by 6nz** [comment]
image
Unknown kid

**Pull request closed without merging**
