### PR TITLE
Added many stuff

### PR DESCRIPTION
**Pull request by 6nz**
Added **auto-login** example, user data dumping to auth file on login,removed unused modules, replaced **sys.exit** with **os._exit(1)** cuz **os._exit** calls the C function **_exit()** which does an immediate program termination(**sys.exit** can't stop threads), added a few "_detailed_" comments
+smaller keyauth.py file size when compiled bc removed all the unused modules

### CODE REVIEW

**Comment by wnelson03** [comment]
@mazkdevf doing university course work rn. If you test it and it runs fine, feel free to merge 👍

**Comment by mazkdevf** [comment]
> @mazkdevf doing university course work rn. If you test it and it runs fine, feel free to merge 👍

@wnelson03 👌 👍🏻

**Comment by mazkdevf** [comment]
ill check later

**Comment by 6nz** [comment]
goofy ahh

**Pull request merged**
